version: "3"
#
# Services definitions
#
services:
  selenium:
    image: 'selenium/standalone-chrome'
    volumes:
      - '/dev/shm:/dev/shm'
    environment:
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_CONCURRENCY=10
      - NODE_MAX_SESSION=10
      - NODE_BROWSER_TIMEOUT=50000
    ports:
      - 4444:4444
